feat: Add SME2p1 int8 mop4a micro-kernel
Added a 0.5VLx8VL (2vsx32vs) quarter product
micro-kernel function for matrix multiplication.

Signed-off-by: Felix Thomasmathibalan <felixjohnny.thomasmathibalan@arm.com>

Reviewed-by: Felix Johnny Thomasmathibalan <felixjohnny.thomasmathibalan@arm.com>
Reviewed-by: Viet-Hoa Do <viet-hoa.do@arm.com>
Approved-by: Viet-Hoa Do <viet-hoa.do@arm.com>

diff --git a/.gitlab/ci/kleidiai.yml b/.gitlab/ci/kleidiai.yml
--- a/.gitlab/ci/kleidiai.yml
+++ b/.gitlab/ci/kleidiai.yml
@@ -615,10 +615,14 @@ test-examples-sme-fvp:
   stage: test
   needs:
     - build-examples
+  variables:
+    # Enable MOP4 for SME2.1 examples.
+    FVP_MODEL_EXTRA: "-C cluster0.sve.has_sme_mop4=1"
   script:
     # Generate test script with negative and positive tests
     - |
       echo -e "#\!/bin/bash -ex"                                         > run_tests.sh
+      echo "set -o pipefail"                                              >> run_tests.sh
       find build -type f -perm -a=x -name \*_sme\* -print0 | \
       while read -d '' EXAMPLE; do
         echo "echo ---------------------------------------------------" >> run_tests.sh
